openapi: 3.0.0
info:
  title: My API
  description: 
  version: 0.0.1
servers:
  - url: http://localhost:3002
    description: Development server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Creates a new post.
      description: Optional
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /txt:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
  /csv:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
          
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name

