import express from 'express';
import path from 'path';
import cookieParser from 'cookie-parser';
import logger from 'morgan';
import indexRouter from './routes/index';
import fileReaderRouter from './routes/fileReaders';
import swaggerUI from "swagger-ui-express";
const YAML = require('yamljs');
const swaggerDocument = YAML.load(path.join(__dirname, '..', 'openapi', 'definitions.yaml'));

const app = express();
app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(swaggerDocument));
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, '../public')));
app.use('/', indexRouter);
app.use('/read-file', fileReaderRouter);
export default app;